// <auto-generated />
using System;
using JustBlog.Entities.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JustBlog.Entities.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0-rc.2.22472.11")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("JustBlog.Entities.Entities.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AboutMe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("56de49b5-22c6-4e3e-8e8c-6adb86a24cc9"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "48c0dfe4-e421-4e52-9f40-b39535e2d4d8",
                            Email = "user@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "USER@EXAMPLE.COM",
                            NormalizedUserName = "USER@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAENwXE96JpUljasCwbIvXiI6y4egJqFJrb4Kmp6MNbpq76gHIhRjOPzTiwJrC3hoEoQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "user@example.com"
                        },
                        new
                        {
                            Id = new Guid("ac924737-2076-4cab-983a-f184ef7f2f1b"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "647925c5-013e-45bd-b9f1-89b290fa8382",
                            Email = "user1@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "USER1@EXAMPLE.COM",
                            NormalizedUserName = "USER1@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAENOzdcCZQYfzfFVtJviLlvqT+MwR4wH9fLRpEPPEB8inbeMjPc+ZXp2B0mmi/tIUtQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "user1@example.com"
                        },
                        new
                        {
                            Id = new Guid("da1d155d-2eb4-46ad-81ed-ddd99ea58b4e"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f40d1618-14f9-4251-a000-cb395f7a5bd1",
                            Email = "user2@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "USER2@EXAMPLE.COM",
                            NormalizedUserName = "USER2@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEGqMgmq/F7PCeMTsaUkZDuD4OFUCAnP16Wil6Ytl9P8Z4X5pGleWyIgv6KWOwKQD/g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "user2@example.com"
                        },
                        new
                        {
                            Id = new Guid("1c917bbc-383b-4b7e-9fce-bfd76f2f4aed"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "99e15c65-4e11-43fc-9222-7d00f0e19206",
                            Email = "owner@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "OWNER@EXAMPLE.COM",
                            NormalizedUserName = "OWNER@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEEbYIf4+ZIIy3RkT15CmHedm4AzuWa/nIzVSa2/uXs/Exj6Q8ixKvU/K0XUGvnkUog==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "owner@example.com"
                        },
                        new
                        {
                            Id = new Guid("c92627c0-9156-494d-bc90-ad381f136852"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1f3cbf3b-77d2-4018-953d-9f3b93d7515b",
                            Email = "owner1@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "OWNER1@EXAMPLE.COM",
                            NormalizedUserName = "OWNER1@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEAdEYYfteN9Rkpqv8JAMjj2weL4O1CB+t0Uz9zljdLBI3ybv2S34EeKt6+FaggpBew==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "owner1@example.com"
                        },
                        new
                        {
                            Id = new Guid("55c97cf2-48a1-455c-80e0-307cca32e4fa"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d32ce5af-e0f7-4bee-8eeb-8217c2161a92",
                            Email = "owner2@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "OWNER2@EXAMPLE.COM",
                            NormalizedUserName = "OWNER2@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAECkf4WVaZpN8Dq1RiMALFYqtR0PPcuuOo9Pr6QFxf1KsD3rn+ODg+yAFo1RNfBM4Rw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "owner2@example.com"
                        },
                        new
                        {
                            Id = new Guid("8b5ed246-11b1-4df6-b36a-9be399f60891"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "72fb7b43-76f8-47d9-a650-da837c58f868",
                            Email = "contributor@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "CONTRIBUTOR@EXAMPLE.COM",
                            NormalizedUserName = "CONTRIBUTOR@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEJXIDQaMwTMjn1fwQ8WPYvCG5e3gDALzYuJL3pDVSsnDwGvRd5rSEjbqS5GzpcZsFQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "contributor@example.com"
                        },
                        new
                        {
                            Id = new Guid("aeae5ff8-43cd-4f90-8d9e-234b9c2d14b9"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "9c6aa7b7-0c1c-4076-84ea-18114941d1e6",
                            Email = "contributor1@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "CONTRIBUTOR1@EXAMPLE.COM",
                            NormalizedUserName = "CONTRIBUTOR1@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEDtuAnw5CJPicHWUhnSJS+gYHJbYL45Ia/XU7v5rXL9Qx+7cWleopc7sIUWibid8qA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "contributor1@example.com"
                        },
                        new
                        {
                            Id = new Guid("70369848-8782-4928-b8e3-106db74c5f3f"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "4bed6519-5dbe-4723-9ab3-7b53a1cd3c3b",
                            Email = "contributor2@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "CONTRIBUTOR2@EXAMPLE.COM",
                            NormalizedUserName = "CONTRIBUTOR2@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEOyJUkl7Wj++2CPahh6E29A1nT/FuPYy0i9Zy6JlYff97WfI1RDthE/eHRwtVimr1Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "contributor2@example.com"
                        });
                });

            modelBuilder.Entity("JustBlog.Entities.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("UrlSlug")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UrlSlug")
                        .IsUnique()
                        .HasFilter("[UrlSlug] IS NOT NULL");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bf2a84ab-68f7-482d-8dcd-f2c0f9028049"),
                            Description = "Description 1",
                            Name = "Category 1",
                            UrlSlug = "category-1"
                        },
                        new
                        {
                            Id = new Guid("e1a767ca-708a-4392-bf9a-c16dcf9ab04f"),
                            Description = "Description 2",
                            Name = "Category 2",
                            UrlSlug = "category-2"
                        },
                        new
                        {
                            Id = new Guid("4245cf7a-4aa2-4467-b411-518830a4a43a"),
                            Description = "Description 3",
                            Name = "Category 3",
                            UrlSlug = "category-3"
                        });
                });

            modelBuilder.Entity("JustBlog.Entities.Entities.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Body")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Header")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("JustBlog.Entities.Entities.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PostedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Published")
                        .HasColumnType("bit");

                    b.Property<int?>("RateCount")
                        .HasColumnType("int");

                    b.Property<string>("ShortDescription")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("TotalRate")
                        .HasColumnType("int");

                    b.Property<string>("UrlSlug")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("ViewCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UrlSlug")
                        .IsUnique()
                        .HasFilter("[UrlSlug] IS NOT NULL");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("37026059-494f-499e-ac1a-17fb1f8736b0"),
                            CategoryId = new Guid("bf2a84ab-68f7-482d-8dcd-f2c0f9028049"),
                            Content = "Content 1",
                            Description = "Description 1",
                            Modified = new DateTime(2022, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PostedOn = new DateTime(2022, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Published = true,
                            RateCount = 2,
                            ShortDescription = "Short Description 1",
                            Title = "Post 1",
                            TotalRate = 10,
                            UrlSlug = "post-1",
                            ViewCount = 2
                        },
                        new
                        {
                            Id = new Guid("8d248b4b-2a7d-4a85-a2d9-9688ce5aa9a2"),
                            CategoryId = new Guid("e1a767ca-708a-4392-bf9a-c16dcf9ab04f"),
                            Content = "Content 2",
                            Description = "Description 2",
                            Modified = new DateTime(2022, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PostedOn = new DateTime(2022, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Published = true,
                            RateCount = 5,
                            ShortDescription = "Short Description 2",
                            Title = "Post 2",
                            TotalRate = 15,
                            UrlSlug = "post-2",
                            ViewCount = 5
                        },
                        new
                        {
                            Id = new Guid("274ccdc9-922d-42d3-9931-5448b6a21f21"),
                            CategoryId = new Guid("4245cf7a-4aa2-4467-b411-518830a4a43a"),
                            Content = "Content 3",
                            Description = "Description 3",
                            Modified = new DateTime(2022, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PostedOn = new DateTime(2022, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Published = true,
                            RateCount = 10,
                            ShortDescription = "Short Description 3",
                            Title = "Post 3",
                            TotalRate = 10,
                            UrlSlug = "post-3",
                            ViewCount = 10
                        });
                });

            modelBuilder.Entity("JustBlog.Entities.Entities.PostTag", b =>
                {
                    b.Property<Guid>("PostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PostId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("PostTags");

                    b.HasData(
                        new
                        {
                            PostId = new Guid("37026059-494f-499e-ac1a-17fb1f8736b0"),
                            TagId = new Guid("bc341849-ae9c-4dc6-8735-ac10d1d76ac1")
                        },
                        new
                        {
                            PostId = new Guid("37026059-494f-499e-ac1a-17fb1f8736b0"),
                            TagId = new Guid("90ee6cd8-7e27-43ea-95a2-1cb21edff54e")
                        },
                        new
                        {
                            PostId = new Guid("8d248b4b-2a7d-4a85-a2d9-9688ce5aa9a2"),
                            TagId = new Guid("90ee6cd8-7e27-43ea-95a2-1cb21edff54e")
                        },
                        new
                        {
                            PostId = new Guid("8d248b4b-2a7d-4a85-a2d9-9688ce5aa9a2"),
                            TagId = new Guid("48c1c139-b86e-4811-899b-05d81814a394")
                        },
                        new
                        {
                            PostId = new Guid("274ccdc9-922d-42d3-9931-5448b6a21f21"),
                            TagId = new Guid("48c1c139-b86e-4811-899b-05d81814a394")
                        },
                        new
                        {
                            PostId = new Guid("274ccdc9-922d-42d3-9931-5448b6a21f21"),
                            TagId = new Guid("bc341849-ae9c-4dc6-8735-ac10d1d76ac1")
                        });
                });

            modelBuilder.Entity("JustBlog.Entities.Entities.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("UrlSlug")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UrlSlug")
                        .IsUnique()
                        .HasFilter("[UrlSlug] IS NOT NULL");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bc341849-ae9c-4dc6-8735-ac10d1d76ac1"),
                            Description = "Description 1",
                            Name = "Tag 1",
                            UrlSlug = "tag-1"
                        },
                        new
                        {
                            Id = new Guid("90ee6cd8-7e27-43ea-95a2-1cb21edff54e"),
                            Description = "Description 2",
                            Name = "Tag 2",
                            UrlSlug = "tag-2"
                        },
                        new
                        {
                            Id = new Guid("48c1c139-b86e-4811-899b-05d81814a394"),
                            Description = "Description 3",
                            Name = "Tag 3",
                            UrlSlug = "tag-3"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("e9d69a07-8601-4d43-8e80-190e97bb068f"),
                            Name = "Blog Owner",
                            NormalizedName = "BLOG OWNER"
                        },
                        new
                        {
                            Id = new Guid("9b47fbf8-e0b6-48af-8fa9-3636c7f815ec"),
                            Name = "User",
                            NormalizedName = "USER"
                        },
                        new
                        {
                            Id = new Guid("dc71a2ee-5450-4827-a74a-4ee47043450b"),
                            Name = "Contributor",
                            NormalizedName = "CONTRIBUTOR"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("55c97cf2-48a1-455c-80e0-307cca32e4fa"),
                            RoleId = new Guid("e9d69a07-8601-4d43-8e80-190e97bb068f")
                        },
                        new
                        {
                            UserId = new Guid("c92627c0-9156-494d-bc90-ad381f136852"),
                            RoleId = new Guid("e9d69a07-8601-4d43-8e80-190e97bb068f")
                        },
                        new
                        {
                            UserId = new Guid("1c917bbc-383b-4b7e-9fce-bfd76f2f4aed"),
                            RoleId = new Guid("e9d69a07-8601-4d43-8e80-190e97bb068f")
                        },
                        new
                        {
                            UserId = new Guid("56de49b5-22c6-4e3e-8e8c-6adb86a24cc9"),
                            RoleId = new Guid("9b47fbf8-e0b6-48af-8fa9-3636c7f815ec")
                        },
                        new
                        {
                            UserId = new Guid("ac924737-2076-4cab-983a-f184ef7f2f1b"),
                            RoleId = new Guid("9b47fbf8-e0b6-48af-8fa9-3636c7f815ec")
                        },
                        new
                        {
                            UserId = new Guid("da1d155d-2eb4-46ad-81ed-ddd99ea58b4e"),
                            RoleId = new Guid("9b47fbf8-e0b6-48af-8fa9-3636c7f815ec")
                        },
                        new
                        {
                            UserId = new Guid("70369848-8782-4928-b8e3-106db74c5f3f"),
                            RoleId = new Guid("dc71a2ee-5450-4827-a74a-4ee47043450b")
                        },
                        new
                        {
                            UserId = new Guid("aeae5ff8-43cd-4f90-8d9e-234b9c2d14b9"),
                            RoleId = new Guid("dc71a2ee-5450-4827-a74a-4ee47043450b")
                        },
                        new
                        {
                            UserId = new Guid("8b5ed246-11b1-4df6-b36a-9be399f60891"),
                            RoleId = new Guid("dc71a2ee-5450-4827-a74a-4ee47043450b")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("JustBlog.Entities.Entities.Comment", b =>
                {
                    b.HasOne("JustBlog.Entities.Entities.Post", "Post")
                        .WithMany()
                        .HasForeignKey("PostId");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("JustBlog.Entities.Entities.Post", b =>
                {
                    b.HasOne("JustBlog.Entities.Entities.Category", "Category")
                        .WithMany("Posts")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("JustBlog.Entities.Entities.PostTag", b =>
                {
                    b.HasOne("JustBlog.Entities.Entities.Post", "Post")
                        .WithMany("PostTags")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JustBlog.Entities.Entities.Tag", "Tag")
                        .WithMany("PostTag")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("JustBlog.Entities.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("JustBlog.Entities.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JustBlog.Entities.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("JustBlog.Entities.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JustBlog.Entities.Entities.Category", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("JustBlog.Entities.Entities.Post", b =>
                {
                    b.Navigation("PostTags");
                });

            modelBuilder.Entity("JustBlog.Entities.Entities.Tag", b =>
                {
                    b.Navigation("PostTag");
                });
#pragma warning restore 612, 618
        }
    }
}
